window.esdocSearchIndex = [
  [
    "./smileguess-server/models/game.js~game",
    "class/smileguess-server/models/Game.js~Game.html",
    "<span>Game</span> <span class=\"search-result-import-path\">./smileguess-server/models/Game.js</span>",
    "class"
  ],
  [
    "./smileguess-server/collections/games.js~games",
    "class/smileguess-server/collections/Games.js~Games.html",
    "<span>Games</span> <span class=\"search-result-import-path\">./smileguess-server/collections/Games.js</span>",
    "class"
  ],
  [
    "./smileguess-server/models/user.js~user",
    "class/smileguess-server/models/User.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">./smileguess-server/models/User.js</span>",
    "class"
  ],
  [
    "./smileguess-server/collections/users.js~users",
    "class/smileguess-server/collections/Users.js~Users.html",
    "<span>Users</span> <span class=\"search-result-import-path\">./smileguess-server/collections/Users.js</span>",
    "class"
  ],
  [
    "./smileguess-server/sockets/dummysocketdata.js~dummy",
    "variable/index.html#static-variable-dummy",
    "<span>dummy</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/dummySocketData.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/onconnect.js~onconnect",
    "variable/index.html#static-variable-onConnect",
    "<span>onConnect</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/onConnect.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/ondisconnect.js~ondisconnect",
    "variable/index.html#static-variable-onDisconnect",
    "<span>onDisconnect</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/onDisconnect.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/sendcluemessage.js~sendcluemessage",
    "variable/index.html#static-variable-sendClueMessage",
    "<span>sendClueMessage</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/sendClueMessage.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/sendguessmessage.js~sendguessmessage",
    "variable/index.html#static-variable-sendGuessMessage",
    "<span>sendGuessMessage</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/sendGuessMessage.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/sendplayerjoingame.js~sendplayerjoingame",
    "variable/index.html#static-variable-sendPlayerJoinGame",
    "<span>sendPlayerJoinGame</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/sendPlayerJoinGame.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/sendprompt.js~sendprompt",
    "variable/index.html#static-variable-sendPrompt",
    "<span>sendPrompt</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/sendPrompt.js</span>",
    "variable"
  ],
  [
    "./smileguess-server/sockets/sendwinner.js~sendwinner",
    "variable/index.html#static-variable-sendWinner",
    "<span>sendWinner</span> <span class=\"search-result-import-path\">./smileguess-server/sockets/sendWinner.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "smileguess-server/collections/games.js",
    "file/smileguess-server/collections/Games.js.html",
    "smileguess-server/collections/Games.js",
    "file"
  ],
  [
    "smileguess-server/collections/games.js~games#alltimegamecount",
    "class/smileguess-server/collections/Games.js~Games.html#instance-member-allTimeGameCount",
    "smileguess-server/collections/Games.js~Games#allTimeGameCount",
    "member"
  ],
  [
    "smileguess-server/collections/games.js~games#constructor",
    "class/smileguess-server/collections/Games.js~Games.html#instance-constructor-constructor",
    "smileguess-server/collections/Games.js~Games#constructor",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#creategame",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-createGame",
    "smileguess-server/collections/Games.js~Games#createGame",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#destroy",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-destroy",
    "smileguess-server/collections/Games.js~Games#destroy",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#fullgames",
    "class/smileguess-server/collections/Games.js~Games.html#instance-member-fullGames",
    "smileguess-server/collections/Games.js~Games#fullGames",
    "member"
  ],
  [
    "smileguess-server/collections/games.js~games#generategameid",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-generateGameId",
    "smileguess-server/collections/Games.js~Games#generateGameId",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#getnextopengame",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-getNextOpenGame",
    "smileguess-server/collections/Games.js~Games#getNextOpenGame",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#insert",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-insert",
    "smileguess-server/collections/Games.js~Games#insert",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#io",
    "class/smileguess-server/collections/Games.js~Games.html#instance-member-io",
    "smileguess-server/collections/Games.js~Games#io",
    "member"
  ],
  [
    "smileguess-server/collections/games.js~games#movetofullgames",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-moveToFullGames",
    "smileguess-server/collections/Games.js~Games#moveToFullGames",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#movetoopengames",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-moveToOpenGames",
    "smileguess-server/collections/Games.js~Games#moveToOpenGames",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#opengames",
    "class/smileguess-server/collections/Games.js~Games.html#instance-member-openGames",
    "smileguess-server/collections/Games.js~Games#openGames",
    "member"
  ],
  [
    "smileguess-server/collections/games.js~games#queue",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-queue",
    "smileguess-server/collections/Games.js~Games#queue",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#removegamesummary",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-removeGameSummary",
    "smileguess-server/collections/Games.js~Games#removeGameSummary",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#retrieve",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-retrieve",
    "smileguess-server/collections/Games.js~Games#retrieve",
    "method"
  ],
  [
    "smileguess-server/collections/games.js~games#storage",
    "class/smileguess-server/collections/Games.js~Games.html#instance-member-storage",
    "smileguess-server/collections/Games.js~Games#storage",
    "member"
  ],
  [
    "smileguess-server/collections/games.js~games#updatequeue",
    "class/smileguess-server/collections/Games.js~Games.html#instance-method-updateQueue",
    "smileguess-server/collections/Games.js~Games#updateQueue",
    "method"
  ],
  [
    "smileguess-server/collections/users.js",
    "file/smileguess-server/collections/Users.js.html",
    "smileguess-server/collections/Users.js",
    "file"
  ],
  [
    "smileguess-server/collections/users.js~users#addusertocollection",
    "class/smileguess-server/collections/Users.js~Users.html#instance-method-addUserToCollection",
    "smileguess-server/collections/Users.js~Users#addUserToCollection",
    "method"
  ],
  [
    "smileguess-server/collections/users.js~users#constructor",
    "class/smileguess-server/collections/Users.js~Users.html#instance-constructor-constructor",
    "smileguess-server/collections/Users.js~Users#constructor",
    "method"
  ],
  [
    "smileguess-server/collections/users.js~users#createuser",
    "class/smileguess-server/collections/Users.js~Users.html#instance-method-createUser",
    "smileguess-server/collections/Users.js~Users#createUser",
    "method"
  ],
  [
    "smileguess-server/collections/users.js~users#destroy",
    "class/smileguess-server/collections/Users.js~Users.html#instance-method-destroy",
    "smileguess-server/collections/Users.js~Users#destroy",
    "method"
  ],
  [
    "smileguess-server/collections/users.js~users#getone",
    "class/smileguess-server/collections/Users.js~Users.html#instance-method-getOne",
    "smileguess-server/collections/Users.js~Users#getOne",
    "method"
  ],
  [
    "smileguess-server/collections/users.js~users#totaluserscreated",
    "class/smileguess-server/collections/Users.js~Users.html#instance-member-totalUsersCreated",
    "smileguess-server/collections/Users.js~Users#totalUsersCreated",
    "member"
  ],
  [
    "smileguess-server/collections/users.js~users#users",
    "class/smileguess-server/collections/Users.js~Users.html#instance-member-users",
    "smileguess-server/collections/Users.js~Users#users",
    "member"
  ],
  [
    "smileguess-server/config/gamesettings.js",
    "file/smileguess-server/config/gameSettings.js.html",
    "smileguess-server/config/gameSettings.js",
    "file"
  ],
  [
    "smileguess-server/config/routes.js",
    "file/smileguess-server/config/routes.js.html",
    "smileguess-server/config/routes.js",
    "file"
  ],
  [
    "smileguess-server/config/sockets.js",
    "file/smileguess-server/config/sockets.js.html",
    "smileguess-server/config/sockets.js",
    "file"
  ],
  [
    "smileguess-server/config/solutions.js",
    "file/smileguess-server/config/solutions.js.html",
    "smileguess-server/config/solutions.js",
    "file"
  ],
  [
    "smileguess-server/controllers/gamecontroller.js",
    "file/smileguess-server/controllers/GameController.js.html",
    "smileguess-server/controllers/GameController.js",
    "file"
  ],
  [
    "smileguess-server/controllers/usercontroller.js",
    "file/smileguess-server/controllers/UserController.js.html",
    "smileguess-server/controllers/UserController.js",
    "file"
  ],
  [
    "smileguess-server/controllers/utils.js",
    "file/smileguess-server/controllers/utils.js.html",
    "smileguess-server/controllers/utils.js",
    "file"
  ],
  [
    "smileguess-server/models/game.js",
    "file/smileguess-server/models/Game.js.html",
    "smileguess-server/models/Game.js",
    "file"
  ],
  [
    "smileguess-server/models/game.js~game#active",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-active",
    "smileguess-server/models/Game.js~Game#active",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#addplayer",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-addPlayer",
    "smileguess-server/models/Game.js~Game#addPlayer",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#checkguess",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-checkGuess",
    "smileguess-server/models/Game.js~Game#checkGuess",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#constructor",
    "class/smileguess-server/models/Game.js~Game.html#instance-constructor-constructor",
    "smileguess-server/models/Game.js~Game#constructor",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#dealerid",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-dealerId",
    "smileguess-server/models/Game.js~Game#dealerId",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#events",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-events",
    "smileguess-server/models/Game.js~Game#events",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#getprompt",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-getPrompt",
    "smileguess-server/models/Game.js~Game#getPrompt",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#id",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-id",
    "smileguess-server/models/Game.js~Game#id",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#io",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-io",
    "smileguess-server/models/Game.js~Game#io",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#newdealer",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-newDealer",
    "smileguess-server/models/Game.js~Game#newDealer",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#on",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-on",
    "smileguess-server/models/Game.js~Game#on",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#players",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-players",
    "smileguess-server/models/Game.js~Game#players",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#prompt",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-prompt",
    "smileguess-server/models/Game.js~Game#prompt",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#removeplayer",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-removePlayer",
    "smileguess-server/models/Game.js~Game#removePlayer",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#seatsopen",
    "class/smileguess-server/models/Game.js~Game.html#instance-member-seatsOpen",
    "smileguess-server/models/Game.js~Game#seatsOpen",
    "member"
  ],
  [
    "smileguess-server/models/game.js~game#trigger",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-trigger",
    "smileguess-server/models/Game.js~Game#trigger",
    "method"
  ],
  [
    "smileguess-server/models/game.js~game#updateopenseats",
    "class/smileguess-server/models/Game.js~Game.html#instance-method-updateOpenSeats",
    "smileguess-server/models/Game.js~Game#updateOpenSeats",
    "method"
  ],
  [
    "smileguess-server/models/user.js",
    "file/smileguess-server/models/User.js.html",
    "smileguess-server/models/User.js",
    "file"
  ],
  [
    "smileguess-server/models/user.js~user#constructor",
    "class/smileguess-server/models/User.js~User.html#instance-constructor-constructor",
    "smileguess-server/models/User.js~User#constructor",
    "method"
  ],
  [
    "smileguess-server/models/user.js~user#deviceid",
    "class/smileguess-server/models/User.js~User.html#instance-member-deviceId",
    "smileguess-server/models/User.js~User#deviceId",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#emojicoins",
    "class/smileguess-server/models/User.js~User.html#instance-member-emojicoins",
    "smileguess-server/models/User.js~User#emojicoins",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#picture",
    "class/smileguess-server/models/User.js~User.html#instance-member-picture",
    "smileguess-server/models/User.js~User#picture",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#points",
    "class/smileguess-server/models/User.js~User.html#instance-member-points",
    "smileguess-server/models/User.js~User#points",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#socket",
    "class/smileguess-server/models/User.js~User.html#instance-member-socket",
    "smileguess-server/models/User.js~User#socket",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#userid",
    "class/smileguess-server/models/User.js~User.html#instance-member-userId",
    "smileguess-server/models/User.js~User#userId",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#username",
    "class/smileguess-server/models/User.js~User.html#instance-member-username",
    "smileguess-server/models/User.js~User#username",
    "member"
  ],
  [
    "smileguess-server/models/user.js~user#wins",
    "class/smileguess-server/models/User.js~User.html#instance-member-wins",
    "smileguess-server/models/User.js~User#wins",
    "member"
  ],
  [
    "smileguess-server/sockets/dummysocketdata.js",
    "file/smileguess-server/sockets/dummySocketData.js.html",
    "smileguess-server/sockets/dummySocketData.js",
    "file"
  ],
  [
    "smileguess-server/sockets/onconnect.js",
    "file/smileguess-server/sockets/onConnect.js.html",
    "smileguess-server/sockets/onConnect.js",
    "file"
  ],
  [
    "smileguess-server/sockets/ondisconnect.js",
    "file/smileguess-server/sockets/onDisconnect.js.html",
    "smileguess-server/sockets/onDisconnect.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendcluemessage.js",
    "file/smileguess-server/sockets/sendClueMessage.js.html",
    "smileguess-server/sockets/sendClueMessage.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendgamechange.js",
    "file/smileguess-server/sockets/sendGameChange.js.html",
    "smileguess-server/sockets/sendGameChange.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendguessmessage.js",
    "file/smileguess-server/sockets/sendGuessMessage.js.html",
    "smileguess-server/sockets/sendGuessMessage.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendplayerjoingame.js",
    "file/smileguess-server/sockets/sendPlayerJoinGame.js.html",
    "smileguess-server/sockets/sendPlayerJoinGame.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendprompt.js",
    "file/smileguess-server/sockets/sendPrompt.js.html",
    "smileguess-server/sockets/sendPrompt.js",
    "file"
  ],
  [
    "smileguess-server/sockets/sendwinner.js",
    "file/smileguess-server/sockets/sendWinner.js.html",
    "smileguess-server/sockets/sendWinner.js",
    "file"
  ],
  [
    "smileguess-server/sockets/socketutils.js",
    "file/smileguess-server/sockets/socketUtils.js.html",
    "smileguess-server/sockets/socketUtils.js",
    "file"
  ],
  [
    "smileguess-server/spec/useragent.js",
    "file/smileguess-server/spec/UserAgent.js.html",
    "smileguess-server/spec/UserAgent.js",
    "file"
  ],
  [
    "smileguess-server/spec/requesttest.js",
    "file/smileguess-server/spec/requestTest.js.html",
    "smileguess-server/spec/requestTest.js",
    "file"
  ],
  [
    "smileguess-server/spec/serversidetests.js",
    "file/smileguess-server/spec/serverSideTests.js.html",
    "smileguess-server/spec/serverSideTests.js",
    "file"
  ],
  [
    "smileguess-server/spec/sockettests.js",
    "file/smileguess-server/spec/socketTests.js.html",
    "smileguess-server/spec/socketTests.js",
    "file"
  ],
  [
    "smileguess-server/spec/support/reporter.js",
    "file/smileguess-server/spec/support/reporter.js.html",
    "smileguess-server/spec/support/reporter.js",
    "file"
  ],
  [
    "smileguess-server/spec/testutils.js",
    "file/smileguess-server/spec/testUtils.js.html",
    "smileguess-server/spec/testUtils.js",
    "file"
  ]
]